FROM node:23.9 AS builder

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install
COPY . .
RUN pnpm run docs:build

# Финальный этап — минимальный образ без веб-сервера
FROM alpine:latest

# Копируем скомпилированные файлы в общий том
COPY --from=builder /app/docs/.vuepress/dist /docs

# Устанавливаем бесконечный цикл, чтобы контейнер не завершался
CMD ["tail", "-f", "/dev/null"]