# Название workflow
name: Build and Deploy VuePress Docs

# Триггер: запуск при пуше в main
on:
  push:
    branches:
      - master

# Задача: сборка и деплой
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu, где Docker уже частично готов

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4
        # Зачем: Загружает код из репозитория (Dockerfile, VuePress-файлы) в рабочую среду.

      # Шаг 2: Настраиваем Docker Buildx в рабочей среде github
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Зачем: Устанавливает Buildx для сборки и пуша образов. Это нужно, даже если Docker есть,
        # так как Buildx добавляет поддержку многоплатформенной сборки и удобный пуш.

      # Шаг 3: Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Зачем: Авторизуемся в Docker Hub, чтобы пушить образ. Секреты берутся из настроек репозитория.

      # Шаг 4: Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # Корневая директория для сборки
          file: ./Dockerfile.prod  # Путь к Dockerfile
          push: true  # Пушим образ после сборки
          tags: digitalstars0/simplevk-php-doc:latest  # Имя образа в Docker Hub
        # Что происходит: Собирает образ (VuePress в Node.js, затем Alpine) и пушит в Docker Hub.

      # Шаг 5: Деплой на сервер через SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3  # Готовое действие для SSH-команд
        with:
          host: ${{ secrets.SERVER_IP }}  # IP сервера из секретов
          username: ${{ secrets.SERVER_USER }}  # Пользователь из секретов
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH-ключ из секретов
          script: |
            docker pull digitalstars0/simplevk-php-doc:latest
            docker-compose -f ${{ secrets.COMPOSE_PATH }} up -d vuepress-prod